// Explicit icon map (keeps the client bundle small — no wildcard react-icons import).
// Add a tech: import its icon here and reference the name from data/*.js.
// Unknown names fall back to a generic code glyph, so the build never breaks.
import {
  SiPython,
  SiCplusplus,
  SiTypescript,
  SiJavascript,
  SiPostgresql,
  SiGnubash,
  SiPytorch,
  SiTensorflow,
  SiScikitlearn,
  SiHuggingface,
  SiNumpy,
  SiPandas,
  SiOpencv,
  SiLangchain,
  SiDocker,
  SiKubernetes,
  SiGithubactions,
  SiTerraform,
  SiPrometheus,
  SiGrafana,
  SiFastapi,
  SiNodedotjs,
  SiApachekafka,
  SiMongodb,
  SiRedis,
  SiReact,
  SiNextdotjs,
  SiTailwindcss,
  SiFramer,
} from "react-icons/si";
import {
  FaMagnifyingGlass,
  FaRobot,
  FaBookOpen,
  FaCode,
  FaGraduationCap,
  FaStar,
  FaCodeBranch,
  FaDatabase,
  FaGears,
  FaChartLine,
  FaTerminal,
  FaBrain,
} from "react-icons/fa6";

const ICONS = {
  SiPython,
  SiCplusplus,
  SiTypescript,
  SiJavascript,
  SiPostgresql,
  SiGnubash,
  SiPytorch,
  SiTensorflow,
  SiScikitlearn,
  SiHuggingface,
  SiNumpy,
  SiPandas,
  SiOpencv,
  SiLangchain,
  SiDocker,
  SiKubernetes,
  SiGithubactions,
  SiTerraform,
  SiPrometheus,
  SiGrafana,
  SiFastapi,
  SiNodedotjs,
  SiApachekafka,
  SiMongodb,
  SiRedis,
  SiReact,
  SiNextdotjs,
  SiTailwindcss,
  SiFramer,
  FaMagnifyingGlass,
  FaRobot,
  FaBookOpen,
  FaCode,
  FaGraduationCap,
  FaStar,
  FaCodeBranch,
  FaDatabase,
  FaGears,
  FaChartLine,
  FaTerminal,
  FaBrain,
};

export function resolveIcon(name) {
  return (name && ICONS[name]) || FaCode;
}
